### ISSUE TITLE
Skills window : multiselection enable

### ISSUE THREAD

**Issue by d0tiKs** [ununseptium/skill-calculator#19]
As you can in the picture down below, it is possible to select multiple skills variation at once, and even the master modification that should be selectable at all, in consequence the description has some trouble to refresh.
[visual here](http://imgur.com/qfjHv8L)

P.S : it would be nice to be able to save/share a build, curently switching skills or windows inside the calculator reset almost everything (on Chrome with adBlock).
P.P.S english isn't my native language sorry if I made mistakes.

**Comment by ununseptium** [comment]
**Thanks for your feedback. I really appreciate it!**

The possibility to select multiple skills and mods at once is a result of my lazyness. Miodec's first "non-angular" version of the skill calculator already only allowed to select one mod at a time and so on...

But as i rewrote the whole thing, the "animations" stuff (including hover states of the skills/mods) of the re-implementation become a much lower priority.

I also have some local changes in the pipeline which are "save/share a build" related and would also resolve the multiple selection issue.

But i am pretty lazy right now and i don't know when i'm going to finish my work on that feature.

Again, thanks for your contribution to this project.

Sincerely,
Tim
