### ISSUE TITLE
Data handling should be done via Angular.js

### ISSUE THREAD

**Issue by ununseptium** [ununseptium/skill-calculator#9]
rearrange how the data is stored and handled on the site

**Comment by forrestab** [comment]
How do you want to store the data, in json files or db? My personal optinion (because there isn't much and it is static) would be to move to json files.

**Comment by StevenKrebs** [comment]
that`s what's going to happen anyway since the code base will move over to angular and the app is hosted on node via heroku.

**Comment by forrestab** [comment]
Just asking, is there a reason for hosting on heroku vs just github static pages?

**Comment by ununseptium** [comment]
@forrestab mainly because the heroku integration of travis is kinda cool and with all the heroku pipeline feature we've also a pretty cool workflow.
For example: When you do a pull-request and the build succeeds travis deploys a "staging" app for review purposes which everyone can check out even without accepting the actual pull-request.

**Comment by ununseptium** [comment]
So i made a development branch for the angular data handling. 
The Pull-Request ( #10 ) is still work in progress until i redone the whole thing completely.

**Comment by ununseptium** [comment]
https://github.com/ununseptium/skill-calculator/pull/10
